version: '3.9'

services:
  backend:
    build:
      context: ./backend-django
    container_name: backend
    volumes:
      - ./backend-django/backend:/backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elasticsearch

  frontend:
    build:
      context: ./frontend/frontend
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

volumes:
  postgres_data: 

